apiVersion: v1
kind: Service
metadata:
  name: {{ template "sternsoft.fullname" . }}-admin-fe
  labels:
    app: {{ template "sternsoft.name" . }}-admin-fe
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.adminFe.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.adminFe.type }}
  {{- if (or (eq .Values.service.adminFe.type "LoadBalancer") (eq .Values.service.adminFe.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.adminFe.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ (and (eq .Values.service.adminFe.type "LoadBalancer") (not (empty .Values.service.adminFe.ports.http))) | ternary .Values.service.adminFe.ports.http "80" }}
      targetPort: container
      {{- if (and (eq .Values.service.adminFe.type "NodePort") (not (empty .Values.service.adminFe.ports.http))) }}
      nodePort: {{ .Values.service.adminFe.ports.http }}
      {{- end }}
  selector:
    app: {{ template "sternsoft.name" . }}-admin-fe
    release: {{ .Release.Name }}
