images:
  admin:
    repository: cvtecregistry.azurecr.io/ninet
    tag: 1.0.0
  api:
    repository: nginx
    tag: latest
  mongoExpress:
    repository: mongo-express
    tag: 0.49.0

config:
  clusterProvider: aks
  trainingduedateCronSchedule: "0 * * * *"
  trainingarchiveCronSchedule: "0 * * * *"
  calenderreminderadvanceCronSchedule: "0 * * * *"
  alertpushCronSchedule: "0 * * * *"
  alertsarchiveCronSchedule: "0 * * * *"
  cronToken: ""
  imagePullPolicy: Always
  updateStrategy: RollingUpdate
  admin:
    baseUrl: ""
    hostname: ""
  api:
    internal: false
    appDescription: "CVTec Dashboard"
    appKeywords: "CVTec Dashboard"
    appTitle: "CVTec Dashboard"
    azureContainer: ""
    azureInstrumentationKey: ""
    azureStorageAccessKey: ""
    azureStorageAccount: ""
    baseUrl: ""
    clientKey: ""
    dbConfigUri: ""
    debug: ""
    dockerRegistryServerPassword: ""
    dockerRegistryServerUrl: ""
    dockerRegistryServerUsername: ""
    fileSaveLocation: ""
    firebaseConfig: ""
    firebaseDB: ""
    hostname: ""
    mailDomain: ""
    mailFromWho: ""
    mailgunApiKey: ""
    maxVoteNumEveryDay: ""
    sessionSecret: ""
    toolsClientKey: ""
    toolsDomain: ""
    twilioAccountSid: ""
    twilioAuthToken: ""
    twilioPhoneNumber: ""
    websiteHttploggingRetentionDays: ""
    websitesEnableAppServiceStorage: ""
  mongodb:
    customConfig: ""
    database: sternsoft
    host: ""
    internal: true
    password: P@ssw0rd
    pause: true
    port: 27017
    prometheus: false
    terminationPolicy: Delete
    url: ""
    username: ""
    version: 4.1.13
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    versionMap:
      3.4-v3: 3.4
      3.4.14: 3.4.17
      3.4-v4: 3.4.22
      3.4.22: 3.4.22
      3.6-v3: 3.6
      3.6.8: 3.6.8
      3.6-v4: 3.6.13
      3.6.13: 3.6.13
      4.0-v1: 4.0.5
      4.0.5-v1: 4.0.5
      4.0.3: 4.0.3
      4.0.5-v2: 4.0.5
      4.0-v2: 4.0.11
      4.0.11: 4.0.11
      4.1.7-v1: 4.1.7
      4.1.4: 4.1.4
      4.1.7-v2: 4.1.7-v2
      4.1.13: 4.1.13
      4.1: 4.1.13
    replicaSet:
      enabled: false
      replicas: 3
    shardTopology:
      enabled: false
      configServer:
        replicas: 3
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
      mongos:
        replicas: 2
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
      shard:
        shards: 3
        replicas: 2
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
  mongoExpress:
    enabled: false
    password: pass
    username: admin

service:
  admin:
    type: NodePort
    externalTrafficPolicy: Cluster
    ports:
      http: ""
  api:
    type: NodePort
    externalTrafficPolicy: Cluster
    ports:
      http: ""
  mongoExpress:
    type: NodePort
    externalTrafficPolicy: Cluster
    ports:
      http: ""
  mongodb:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    ports:
      mongodb: ""

ingress:
  admin:
    certificate: ""
    enabled: false
    hostname: ""
    tls: false
    issuer:
      name: letsencrypt-staging
  api:
    certificate: ""
    enabled: false
    hostname: ""
    tls: false
    issuer:
      name: letsencrypt-staging
  mongoExpress:
    certificate: ""
    enabled: false
    hostname: ""
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ""
  size: 1Gi
  storageClass: ""
  velero:
    enabled: false
  stash:
    bucket: ""
    container: ""
    enabled: false
    endpoint: s3.amazonaws.com
    keepLast: 30
    paused: false
    prefix: stash
    schedule: "0 0 * * *"
    secret: stash-config-stash-config
    type: s3
    restore:
      snapshot:
        mongodb: ""

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
