apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sternsoft.fullname" . }}-api
  labels:
    app: {{ template "sternsoft.name" . }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: lifecycle
                  operator: In
                  values:
                    - spot
    containers:
      - name: {{ template "sternsoft.fullname" . }}-api
        image: {{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}
        imagePullPolicy: {{ .Values.config.imagePullPolicy }}
        ports:
          - name: container
            containerPort: 80
        env:
          - name: WEBSITE_HTTPLOGGING_RETENTION_DAYS
            valueFrom:
              configMapKeyRef:
                name: {{ template "sternsoft.fullname" . }}
                key: website_httplogging_retention_days
        livenessProbe:
          httpGet:
            path: /
            port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
        readinessProbe:
          httpGet:
            path: /
            port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
