{{- if .Values.config.toolsApi.internal }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sternsoft.fullname" . }}-tools-api
  labels:
    app: {{ template "sternsoft.name" . }}-tools-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "sternsoft.name" . }}-tools-api
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "sternsoft.name" . }}-tools-api
        release: {{ .Release.Name }}
      {{- if .Values.persistence.velero.enabled }}
      annotations:
        backup.velero.io/backup-volumes: data
      {{- end }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: lifecycle
                    operator: In
                    values:
                      - spot
      containers:
        - name: {{ template "sternsoft.fullname" . }}-tools-api
          image: {{ .Values.images.toolsApi.repository }}:{{ .Values.images.toolsApi.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 8500
          env:
            - name: PORT
              value: '8500'
            - name: WEBSITES_PORT
              value: '8500'
            - name: APP_DESCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_app_description
            - name: APP_KEYWORDS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_app_keywords
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_app_title
            - name: AZURE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_azure_container
            - name: AZURE_INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_azure_instrumentation_key
            - name: AZURE_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_azure_storage_access_key
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_azure_storage_account
            - name: DB_CONFIG_URI
              valueFrom:
                secretKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_mongodb_url
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_debug
            - name: DOCKER_CUSTOM_IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_docker_custom_image_name
            - name: DOCKER_REGISTRY_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_docker_registry_server_password
            - name: DOCKER_REGISTRY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_docker_registry_server_url
            - name: DOCKER_REGISTRY_SERVER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_docker_registry_server_username
            - name: FILE_SAVE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_file_save_location
            - name: PM2_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_pm2_public_key
            - name: PM2_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_pm2_secret_key
            # - name: TOOLS_DOMAIN
            #   valueFrom:
            #     configMapKeyRef:
            #       name: {{ template "sternsoft.fullname" . }}
            #       key: tools_domain
            - name: TOOLS_SITE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_site_host
            - name: WEBSITE_HTTPLOGGING_RETENTION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_website_httplogging_retention_days
            - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}
                  key: tools_websites_enable_app_service_storage
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}
