{{- if .Values.config.alertsPushCronSchedule }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "sternsoft.fullname" . }}-alerts-push
  labels:
    app: {{ template "sternsoft.name" . }}-alerts-push
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.config.alertsPushCronSchedule | quote }}
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: lifecycle
                        operator: In
                        values:
                          - spot
          containers:
            - name: curl
              image: curlimages/curl:7.71.1
              command:
                - sh
                - -c
                - |
                  curl -v -d "" \
                    -H "authorization: Basic ${TOKEN}" \
                    -H "content-type: application/json" \
                    ${BASE_URL}/api/base/alerts/cronjob/push
              env:
                - name: TOKEN
                  valueFrom:
                    configMapKeyRef:
                      name: {{ template "sternsoft.fullname" . }}
                      key: cron_token
                - name: BASE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ template "sternsoft.fullname" . }}
                      key: api_base_url
{{- end }}
