{{- if (and .Values.config.mongodb.internal (and .Values.config.mongoExpress.enabled .Values.ingress.mongoExpress.enabled)) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "sternsoft.fullname" . }}-mongo-express
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.mongoExpress.tls }}
    {{- if (empty .Values.ingress.mongoExpress.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.mongoExpress.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "sternsoft.name" . }}-mongo-express
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.mongoExpress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.mongoExpress.path }}
            backend:
              serviceName: {{ template "sternsoft.fullname" . }}-mongo-express
              servicePort: http
  {{- if .Values.ingress.mongoExpress.tls }}
  tls:
    - secretName: {{ template "sternsoft.mongo-express-certificate" . }}
      hosts:
        - {{ .Values.ingress.mongoExpress.hostname }}
  {{- end }}
{{- end }}
