apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sternsoftadmin.fullname" . }}-sternsoftadmin
  labels:
    app: {{ template "sternsoftadmin.name" . }}-sternsoftadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "sternsoftadmin.name" . }}-sternsoftadmin
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "sternsoftadmin.name" . }}-sternsoftadmin
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "sternsoftadmin.fullname" . }}-sternsoftadmin
          image: {{ .Values.images.sternsoftadmin.repository }}:{{ .Values.images.sternsoftadmin.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /_data
          env: []
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "sternsoftadmin.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
