apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sternsoft.fullname" . }}-sternsoftadmin
  labels:
    app: {{ template "sternsoft.name" . }}-sternsoftadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ template "sternsoft.fullname" . }}-sternsoftadmin
          image: {{ .Values.images.sternsoftadmin.repository }}:{{ .Values.images.sternsoftadmin.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 3000
          env: 
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "sternsoft.fullname" . }}-sternsoftadmin
                  key: api_base_url
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
