apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sternsoft.fullname" . }}
  labels:
    app: {{ template "sternsoft.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $mongodb := .Values.config.mongodb }}
  {{- if $mongodb.internal }}
  mongodb_host: {{ template "sternsoft.fullname" . }}-mongodb
  {{- else }}
  mongodb_host: {{ $mongodb.host | quote }}
  {{- end }}
  mongodb_database: {{ $mongodb.database | quote }}
  mongodb_port: {{ $mongodb.port | quote }}
  mongodb_username: {{ $mongodb.username | quote }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_username: {{ .Values.config.mongoExpress.username | quote }}
  mongodb_server: {{ template "sternsoft.mongodb-server" . }}
  {{- end }}
  api_base_url: {{ template "sternsoft.api-base-url" . }}
  website_httplogging_retention_days: '7'
