apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sternsoft.fullname" . }}
  labels:
    app: {{ template "sternsoft.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $mongodb := .Values.config.mongodb }}
  {{- if $mongodb.internal }}
  mongodb_host: {{ template "sternsoft.fullname" . }}-mongodb
  {{- else }}
  mongodb_host: {{ $mongodb.host | quote }}
  {{- end }}
  mongodb_database: {{ $mongodb.database | quote }}
  mongodb_port: {{ $mongodb.port | quote }}
  mongodb_username: {{ $mongodb.username | quote }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_username: {{ .Values.config.mongoExpress.username | quote }}
  mongodb_server: {{ template "sternsoft.mongodb-server" . }}
  {{- end }}
  backend_base_url: {{ template "sternsoft.api-base-url" . }}
  admin_domain: {{ template "sternsoft.admin-base-url" . }}
  app_description: 'CVTec Dashboard'
  app_keywords: 'CVTec Dashboard'
  app_title: 'CVTec Dashboard'
  azure_container: {{ .Values.config.api.azureContainer | quote  }}
  azure_storage_account: {{ .Values.config.api.azureStorageAccount | quote  }}
  debug: '*'
  docker_registry_server_url: {{ .Values.config.api.dockerRegistryServerUrl | quote  }}
  docker_registry_server_username: {{ .Values.config.api.dockerRegistryServerUsername | quote  }}
  file_save_location: {{ .Values.config.api.fileSaveLocation | quote  }}
  firebase_config: {{ .Values.config.api.firebaseConfig | quote  }}
  firebase_db: {{ .Values.config.api.firebaseDB | quote  }}
  mail_domain: {{ .Values.config.api.mailDomain | quote  }}
  mail_from_who: {{ .Values.config.api.mailFromWho | quote }}
  max_vote_num_every_day: {{ .Values.config.api.maxVoteNumEveryDay | quote }}
  node_env: 'production'
  port: '8900'
  tools_domain: {{ .Values.config.api.toolsDomain | quote  }}
  twilio_account_sid: {{ .Values.config.api.twilioAccountSid  | quote }}
  twilio_phone_number: {{ .Values.config.api.twilioPhoneNumber  | quote }}
  website_httplogging_retention_days:  {{ .Values.config.api.websiteHttploggingRetentionDays | quote  }}
  websites_enable_app_service_storage:  {{ .Values.config.api.websitesEnableAppServiceStorage | quote  }}
  websites_port: '8900'