apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sternsoft.fullname" . }}
  labels:
    app: {{ template "sternsoft.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $mongodb := .Values.config.mongodb }}
  {{- if $mongodb.internal }}
  mongodb_host: {{ template "sternsoft.fullname" . }}-mongodb
  {{- else }}
  mongodb_host: {{ $mongodb.host | quote }}
  {{- end }}
  mongodb_database: {{ $mongodb.database | quote }}
  mongodb_port: {{ $mongodb.port | quote }}
  mongodb_username: {{ $mongodb.username | quote }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_username: {{ .Values.config.mongoExpress.username | quote }}
  mongodb_server: {{ template "sternsoft.mongodb-server" . }}
  {{- end }}
  admin_fe_domain: {{ template "sternsoft.admin-fe-base-url" . }}
  admin_api_base_url: {{ template "sternsoft.admin-api-base-url" . }}
  app_description: {{ .Values.config.adminApi.appDescription | quote  }}
  app_keywords: {{ .Values.config.adminApi.appKeyword | quote  }}
  app_title: {{ .Values.config.adminApi.appTitle | quote  }}
  azure_container: {{ .Values.config.adminApi.azureContainer | quote  }}
  azure_storage_account: {{ .Values.config.adminApi.azureStorageAccount | quote  }}
  cron_token: {{ .Values.config.cronToken | quote }}
  debug: '*'
  docker_registry_server_url: {{ .Values.config.adminApi.dockerRegistryServerUrl | quote  }}
  docker_registry_server_username: {{ .Values.config.adminApi.dockerRegistryServerUsername | quote  }}
  file_save_location: {{ .Values.config.adminApi.fileSaveLocation | quote  }}
  firebase_config: {{ .Values.config.adminApi.firebaseConfig | quote  }}
  firebase_db: {{ .Values.config.adminApi.firebaseDB | quote  }}
  mail_domain: {{ .Values.config.adminApi.mailDomain | quote  }}
  mail_from_who: {{ .Values.config.adminApi.mailFromWho | quote }}
  max_vote_num_every_day: {{ .Values.config.adminApi.maxVoteNumEveryDay | quote }}
  node_env: 'production'
  tools_domain: {{ .Values.config.adminApi.toolsDomain | quote  }}
  twilio_account_sid: {{ .Values.config.adminApi.twilioAccountSid  | quote }}
  twilio_phone_number: {{ .Values.config.adminApi.twilioPhoneNumber  | quote }}
  website_httplogging_retention_days:  {{ .Values.config.adminApi.websiteHttploggingRetentionDays | quote  }}
  websites_enable_app_service_storage:  {{ .Values.config.adminApi.websitesEnableAppServiceStorage | quote  }}
