apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sternsoft.fullname" . }}
  labels:
    app: {{ template "sternsoft.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mongodb := .Values.config.mongodb }}
  mongodb_url: {{ $mongodb.url | b64enc }}
  mongodb_password: {{ $mongodb.password | b64enc }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_password: {{ .Values.config.mongoExpress.password | b64enc }}
  {{- end }}
