apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sternsoft.fullname" . }}
  labels:
    app: {{ template "sternsoft.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mongodb := .Values.config.mongodb }}
  mongodb_url: {{ (include "sternsoft.mongodb-url" .) | b64enc }}
  mongodb_password: {{ $mongodb.password | b64enc }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_password: {{ .Values.config.mongoExpress.password | b64enc }}
  {{- end }}
  azure_instrumentation_key: {{ .Values.config.adminApi.azureInstrumentationKey | b64enc }}
  azure_storage_access_key: {{ .Values.config.adminApi.azureStorageAccessKey | b64enc }}
  client_key: {{ .Values.config.adminApi.clientKey | b64enc }}
  # db_config_uri: {{ (include "sternsoft.mongodb-url" .) | b64enc }}
  docker_registry_server_password: {{ .Values.config.adminApi.dockerRegistryServerPassword | b64enc }}
  mailgun_api_key: {{ .Values.config.adminApi.mailgunApiKey | b64enc }}
  session_secret: {{ .Values.config.adminApi.sessionSecret | b64enc }}
  tools_client_key: {{ .Values.config.adminApi.toolsClientKey | b64enc }}
  twilio_auth_token: {{ .Values.config.adminApi.twilioAuthToken | b64enc }}